# Generated by Django 4.1.5 on 2023-06-27 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rutCliente', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombreCliente', models.CharField(max_length=50)),
                ('emailCliente', models.EmailField(max_length=100, unique=True)),
                ('telefonoCliente', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idPoducto', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombreProducto', models.CharField(max_length=50)),
                ('cantidad', models.CharField(max_length=100)),
                ('precio', models.CharField(max_length=100000)),
                ('estadoProducto', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='tipoUsuario',
            fields=[
                ('idTipoUsuario', models.AutoField(db_column='idTipo', primary_key=True, serialize=False, verbose_name='ID_tipo_Usuario')),
                ('tipoUsuario', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('appPaterno', models.CharField(max_length=30)),
                ('appMaterno', models.CharField(max_length=30)),
                ('fechaNacimiento', models.DateField()),
                ('correo', models.EmailField(max_length=100, unique=True)),
                ('telefono', models.CharField(max_length=10)),
                ('activo', models.IntegerField()),
                ('tipoUsuario', models.ForeignKey(db_column='idTipo', on_delete=django.db.models.deletion.CASCADE, to='newProjectWeb.tipousuario')),
            ],
        ),
    ]
